//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoGenerateForm.DATA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime createdAt { get; set; }
        public int createdBy { get; set; }
        public string fields { get; set; }
    }
}
